FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3.5-stretch-build

WORKDIR /usr/app/src

# Fails error message: 'lstat subservice2: no such file or directory'
COPY subservice2 subservice2

# if instead we use 'COPY . .'
# then it will fail at 'cd subservice2' with message: '/bin/sh: 1: cd: can't cd to subservice2'

RUN ls -lah && cd subservice2 && make

CMD ["echo", "Finished"]
